import {
  RestaurantState,
  TableStatus,
  OrderStatus,
  OrderItemStatus,
  LoyaltyTxType,
  PromoType,
  PaymentMethod,
  ReservationStatus,
  ShiftStatus,
  Role,
} from "./types";

export const DEMO_STATE: RestaurantState = {
  users: [
    { id: "u1", pin: "2222", name: "Juan (Mozo)", role: Role.WAITER },
    { id: "u2", pin: "3333", name: "Carlos (Cocina)", role: Role.KITCHEN },
    { id: "u3", pin: "1234", name: "Don Ricardo (Admin)", role: Role.ADMIN },
  ],
  tables: [
    { id: "t1", number: 1, seats: 2, status: TableStatus.FREE, zone: "Salón Principal", x: 10, y: 10 },
    { id: "t2", number: 2, seats: 4, status: TableStatus.FREE, zone: "Salón Principal", x: 30, y: 10 },
    { id: "t3", number: 3, seats: 4, status: TableStatus.FREE, zone: "Salón Principal", x: 50, y: 10 },
    { id: "t4", number: 4, seats: 6, status: TableStatus.FREE, zone: "Terraza", x: 10, y: 40 },
    { id: "t5", number: 5, seats: 2, status: TableStatus.FREE, zone: "Terraza", x: 30, y: 40 },
    { id: "t6", number: 6, seats: 8, status: TableStatus.FREE, zone: "VIP", x: 65, y: 40 },
    { id: "t7", number: 7, seats: 4, status: TableStatus.FREE, zone: "Salón Principal", x: 70, y: 10 },
    { id: "t8", number: 8, seats: 2, status: TableStatus.FREE, zone: "Terraza", x: 50, y: 40 },
  ],
  categories: [
    { id: "cat_especialidades", name: "Platos de la Casa", icon: "Utensils" },
    { id: "cat_carnes", name: "Carnes y Parrilladas", icon: "Beef" },
    { id: "cat_menu_ejecutivo", name: "Menú Ejecutivo", icon: "ChefHat" },
    { id: "cat_sandwichs", name: "Sándwiches y Pichangas", icon: "Sandwich" },
    { id: "cat_ensaladas", name: "Ensaladas y Papas", icon: "Salad" },
    { id: "cat_tragos", name: "Tragos y Aperitivos", icon: "Wine" },
    { id: "cat_bebidas", name: "Bebidas y Cafetería", icon: "Coffee" },
    { id: "cat_postres", name: "Postres", icon: "Cake" }
  ],
  products: [
    // 1. Platos de la Casa (cat_especialidades)
    {
      id: "p_esp1",
      categoryId: "cat_especialidades",
      name: "Camarones de Hierro al Ajo de Hacienda",
      description: "Camarones flambeados y sellados en hierro, apagados con vino reserva y terminados con ajo confitado, mantequilla avellanada y hierbas frescas.",
      price: 12000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp2",
      categoryId: "cat_especialidades",
      name: "Ceviche Hacienda",
      description: "Pulpo, salmón, atún y camarón ecuatoriano con leche de tigre de la casa, palta y láminas de camote frito.",
      price: 13500,
      isAvailable: true,
      allergens: ["Pescado", "Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp3",
      categoryId: "cat_especialidades",
      name: "Machas al estilo Hacienda",
      description: "Machas gratinadas con mantequilla al merkén, vino blanco y queso mantecoso y un toque de limón sutil.",
      price: 17000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp4",
      categoryId: "cat_especialidades",
      name: "Camarones Hacienda",
      description: "Camarón ecuatoriano flameados terminados con mantequilla al merkén, tomate cherry confitado y albahaca fresca.",
      price: 12000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp5",
      categoryId: "cat_especialidades",
      name: "Salmón finca",
      description: "Salmón sellado con ajo confitado y mantequilla, acompañado de cremoso de arroz con camarones.",
      price: 18500,
      isAvailable: true,
      allergens: ["Pescado", "Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp6",
      categoryId: "cat_especialidades",
      name: "Dominio de merluza al romesco",
      description: "Merluza sellada en mantequilla avellanada con papas fritas al romesco y espárragos grillados.",
      price: 14500,
      isAvailable: true,
      allergens: ["Pescado", "Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp7",
      categoryId: "cat_especialidades",
      name: "Congrio aposento",
      description: "Congrio con salsa de marisco acompañado con puré de habas y hortalizas frescas al limón.",
      price: 19000,
      isAvailable: true,
      allergens: ["Pescado", "Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp8",
      categoryId: "cat_especialidades",
      name: "Pulpo solar",
      description: "Pulpo grillado con mantequilla al merkén, puré de camote y verduras salteadas de temporada.",
      price: 17500,
      isAvailable: true,
      allergens: ["Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp9",
      categoryId: "cat_especialidades",
      name: "Lomo liso Estancia",
      description: "Lomo liso grillado, tomate asado y chimichurri hacienda acompañado de pastelera de choclo.",
      price: 16000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp10",
      categoryId: "cat_especialidades",
      name: "Asado de Tira a cocción lenta",
      description: "Corte de costilla de vacuno preparado en cocción muy lenta, acompañado de pastelera de choclo y toques de albahaca.",
      price: 19000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp11",
      categoryId: "cat_especialidades",
      name: "Costillar de cerdo caramelizado",
      description: "Costillar de cerdo preparado a cocción lenta caramelizado y acompañado de papas cuña y crema ácida.",
      price: 13500,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp12",
      categoryId: "cat_especialidades",
      name: "Risotto de champiñones",
      description: "Arroz rizzoteado en una deliciosa y cremosa salsa de champiñones.",
      price: 11500,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp13",
      categoryId: "cat_especialidades",
      name: "Risotto de camarón",
      description: "Arroz rizzoteado en una salsa de marisco con camarón ecuatoriano salteados en mantequilla con vino blanco y queso mantecoso.",
      price: 12500,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp14",
      categoryId: "cat_especialidades",
      name: "Fetuccini al pesto",
      description: "Fetuccini cocidos con laurel y aceite de oliva, en una salsa verde acompañada de pechuga de pollo.",
      price: 11500,
      isAvailable: true,
      allergens: ["Gluten", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp15",
      categoryId: "cat_especialidades",
      name: "Fetuccini al camarón",
      description: "Fetuccini cocido con laurel y aceite de oliva acompañado de camarones ecuatorianos.",
      price: 13000,
      isAvailable: true,
      allergens: ["Gluten", "Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp16",
      categoryId: "cat_especialidades",
      name: "Mariscal caliente",
      description: "Mariscos surtidos calientes preparados al estilo de la casa.",
      price: 8000,
      isAvailable: true,
      allergens: ["Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp17",
      categoryId: "cat_especialidades",
      name: "Paila marina",
      description: "Sopa tradicional de mariscos y pescados de la zona.",
      price: 12000,
      isAvailable: true,
      allergens: ["Mariscos", "Pescado"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp18",
      categoryId: "cat_especialidades",
      name: "Chupe de jaiva",
      description: "Guiso cremoso de jaiba gratinado con queso.",
      price: 9000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos", "Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp19",
      categoryId: "cat_especialidades",
      name: "Chupe de locos",
      description: "Guiso cremoso de locos picados gratinado con queso.",
      price: 13000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos", "Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_esp20",
      categoryId: "cat_especialidades",
      name: "Jardín marino",
      description: "Selección premium de mariscos y pescados fríos para compartir.",
      price: 18000,
      isAvailable: true,
      allergens: ["Mariscos", "Pescado"],
      recipe: [],
      requiresKitchen: true
    },

    // 2. Carnes y Parrilladas (cat_carnes)
    {
      id: "p_car1",
      categoryId: "cat_carnes",
      name: "Bistec a lo pobre",
      description: "Corte de carne de vacuno con cebolla caramelizada, huevo y papas fritas.",
      price: 12000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car2",
      categoryId: "cat_carnes",
      name: "Bistec con agregado",
      description: "Acompañamiento a elección: Arroz, papas fritas, tallarines o puré de camote.",
      price: 10000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car3",
      categoryId: "cat_carnes",
      name: "Churrasco al plato",
      description: "Carne de vacuno acompañado de tomate y palta.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car4",
      categoryId: "cat_carnes",
      name: "Lomo a lo pobre",
      description: "Corte de lomo liso con papas fritas, cebolla caramelizada y huevo frito.",
      price: 14500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car5",
      categoryId: "cat_carnes",
      name: "Lomo con agregado",
      description: "Acompañamiento a elección: Arroz, papas fritas, tallarines o puré de camote.",
      price: 13500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car6",
      categoryId: "cat_carnes",
      name: "Pechuga a lo pobre",
      description: "Pechuga de pollo a la plancha con cebolla caramelizada, papas fritas y huevo.",
      price: 9500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car7",
      categoryId: "cat_carnes",
      name: "Pechuga con agregado",
      description: "Acompañamiento a elección: Arroz, papas fritas, tallarines o puré de camote.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car8",
      categoryId: "cat_carnes",
      name: "Lomo con salsa de champiñón",
      description: "Lomo bañado en salsa de champiñones con arroz, papas fritas, tallarines o puré de camote.",
      price: 14500,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car9",
      categoryId: "cat_carnes",
      name: "Pechuga en salsa de champiñones",
      description: "Pechuga bañado en salsa de champiñones con arroz, papas fritas, tallarines o puré de camote.",
      price: 12000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car10",
      categoryId: "cat_carnes",
      name: "Lomo saltado",
      description: "Tiras de lomo liso salteados con verduras frescas, acompañado de arroz y papas fritas.",
      price: 13000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car11",
      categoryId: "cat_carnes",
      name: "Pollo saltado",
      description: "Tiras de pollo salteados con verduras frescas, acompañado de arroz y papas fritas.",
      price: 10000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car12",
      categoryId: "cat_carnes",
      name: "Parrilla (4 a 5 personas) básica",
      description: "4 cortes de lomo, 3 trozos de pollo, 3 chuletas de cerdo y 4 longanizas. Acompañada de papas cocidas, pebre, sopaipillas y ensalada.",
      price: 45000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car13",
      categoryId: "cat_carnes",
      name: "Parrilla (4 a 5 personas) con chunchules",
      description: "4 cortes de lomo, 3 trozos de pollo, 3 chuletas de cerdo, 4 longanizas y 4 chunchules. Acompañada de papas cocidas, pebre, sopaipillas y ensalada.",
      price: 49000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car14",
      categoryId: "cat_carnes",
      name: "Parrilla (2 personas) básica",
      description: "2 cortes de lomo, 2 trozos de pollo, 2 chuletas de cerdo y 2 longanizas. Acompañada de papas cocidas, pebre, sopaipillas y ensalada.",
      price: 34000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_car15",
      categoryId: "cat_carnes",
      name: "Parrilla Especial con chunchules (2 personas)",
      description: "2 cortes de lomo, 2 trozos de pollo, 2 chuletas de cerdo, 2 longanizas y 2 chunchules. Acompañada de papas cocidas, pebre, sopaipillas y ensalada.",
      price: 37000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },

    // 3. Menú Ejecutivo (cat_menu_ejecutivo)
    {
      id: "p_exec1",
      categoryId: "cat_menu_ejecutivo",
      name: "Pollo mongoliano",
      description: "Tiras de pollo salteadas con cebollín en salsa de soya.",
      price: 7000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec2",
      categoryId: "cat_menu_ejecutivo",
      name: "Carne mongoliana",
      description: "Tiras de carne de vacuno salteadas con cebollín en salsa de soya.",
      price: 7500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec3",
      categoryId: "cat_menu_ejecutivo",
      name: "Chuleta a la plancha",
      description: "Chuleta de cerdo asada a la plancha.",
      price: 7000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec4",
      categoryId: "cat_menu_ejecutivo",
      name: "Chuleta agridulce",
      description: "Chuleta de cerdo bañada en salsa agridulce especial.",
      price: 7000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec5",
      categoryId: "cat_menu_ejecutivo",
      name: "Pollo a la crema",
      description: "Filete de pollo bañado en crema de leche y especias.",
      price: 8000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec6",
      categoryId: "cat_menu_ejecutivo",
      name: "Cremoso de champiñón con palta",
      description: "Guiso cremoso de champiñones servido con palta.",
      price: 8500,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_exec7",
      categoryId: "cat_menu_ejecutivo",
      name: "Cremoso de camarones y verduras salteadas",
      description: "Guiso cremoso de camarones acompañado de verduras de temporada salteadas.",
      price: 8500,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },

    // 4. Sándwiches y Pichangas (cat_sandwichs)
    {
      id: "p_snd1",
      categoryId: "cat_sandwichs",
      name: "Barros luco",
      description: "200 gr de carne de vacuno con queso fundido. Acompañado de papas fritas.",
      price: 6000,
      isAvailable: true,
      allergens: ["Gluten", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd2",
      categoryId: "cat_sandwichs",
      name: "Sándwich Italiano",
      description: "200 gr de carne de vacuno, palta, tomate y mayonesa. Acompañado de papas fritas.",
      price: 6000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd3",
      categoryId: "cat_sandwichs",
      name: "Sándwich Chacarero",
      description: "200 gr de carne de vacuno, tomate, poroto verde y ají verde. Acompañado de papas fritas.",
      price: 7000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd4",
      categoryId: "cat_sandwichs",
      name: "Sándwich Ave mayo",
      description: "Filete de pollo a la plancha desmenuzado con mayonesa. Acompañado de papas fritas.",
      price: 5500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd5",
      categoryId: "cat_sandwichs",
      name: "Sándwich Ave italiano",
      description: "Filete de pollo a la plancha, tomate, palta y mayonesa. Acompañado de papas fritas.",
      price: 5500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd6",
      categoryId: "cat_sandwichs",
      name: "Sándwich Campesino",
      description: "Filete de pollo, queso fundido, champiñones y choclo. Acompañado de papas fritas.",
      price: 6500,
      isAvailable: true,
      allergens: ["Gluten", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd7",
      categoryId: "cat_sandwichs",
      name: "Pichanga para 2 personas",
      description: "Base de papas fritas cubierta con trozos de carne de vacuno, pollo, cerdo, salchicha, tomate, palta, huevo duro y queso fundido.",
      price: 12000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd8",
      categoryId: "cat_sandwichs",
      name: "Pichanga para 4 personas",
      description: "Base de papas fritas cubierta con trozos de carne de vacuno, pollo, cerdo, salchicha, tomate, palta, huevo duro y queso fundido.",
      price: 22000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd9",
      categoryId: "cat_sandwichs",
      name: "Pichanga mar y tierra",
      description: "Base de papas fritas cubierta con trozos de carne de vacuno, pollo, camarones, pulpo, aros de calamar, palta, pimentones, cebolla morada y queso fundido.",
      price: 14000,
      isAvailable: true,
      allergens: ["Mariscos", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd10",
      categoryId: "cat_sandwichs",
      name: "Chorrillana para 2 personas",
      description: "Base de papas fritas cubierta con trozos de carne de vacuno, pollo, salchicha, cebolla caramelizada y huevo frito.",
      price: 12000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd11",
      categoryId: "cat_sandwichs",
      name: "Chorrillana para 4 personas",
      description: "Base de papas fritas cubierta con trozos de carne de vacuno, pollo, salchicha, cebolla caramelizada y huevo frito.",
      price: 22000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd12",
      categoryId: "cat_sandwichs",
      name: "Completo Italiano",
      description: "Pan de completo, vienesa, tomate, palta y mayonesa.",
      price: 2500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd13",
      categoryId: "cat_sandwichs",
      name: "Completo Chucrut",
      description: "Pan de completo, vienesa, chucrut, salsa americana y mayonesa.",
      price: 2000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd14",
      categoryId: "cat_sandwichs",
      name: "Completo Dinámico",
      description: "Pan de completo, vienesa, tomate, palta, chucrut, salsa americana y mayonesa.",
      price: 3000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_snd15",
      categoryId: "cat_sandwichs",
      name: "Completo Especial palta",
      description: "Pan de completo, vienesa, palta y mayonesa.",
      price: 2500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },

    // 5. Ensaladas y Papas (cat_ensaladas)
    {
      id: "p_sal1",
      categoryId: "cat_ensaladas",
      name: "Papas Fritas Medianas",
      description: "Porción mediana de papas fritas crujientes.",
      price: 3000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_sal2",
      categoryId: "cat_ensaladas",
      name: "Papas Fritas Grandes",
      description: "Porción familiar de papas fritas crujientes.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_sal3",
      categoryId: "cat_ensaladas",
      name: "Ensalada César pollo",
      description: "Ensalada césar tradicional, con lechuga fresca, crutones, queso parmesano y trozos de pollo a la plancha.",
      price: 8500,
      isAvailable: true,
      allergens: ["Gluten", "Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_sal4",
      categoryId: "cat_ensaladas",
      name: "Ensalada César camarón",
      description: "Ensalada césar tradicional, con lechuga fresca, crutones, queso parmesano y camarones ecuatorianos salteados.",
      price: 9900,
      isAvailable: true,
      allergens: ["Gluten", "Lácteos", "Mariscos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_sal5",
      categoryId: "cat_ensaladas",
      name: "Ensalada mixta",
      description: "Ensalada fresca surtida de la estación.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },

    // 6. Tragos y Aperitivos (cat_tragos)
    {
      id: "p_trg1",
      categoryId: "cat_tragos",
      name: "Pisco sour",
      description: "Preparación de la casa con pisco chileno, limón y jarabe de goma.",
      price: 3500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg2",
      categoryId: "cat_tragos",
      name: "Pisco sour sabores",
      description: "Sabores variados según temporada.",
      price: 4000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg3",
      categoryId: "cat_tragos",
      name: "Whisky sour",
      description: "Whisky, jugo de limón y jarabe de goma.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg4",
      categoryId: "cat_tragos",
      name: "Amaretto sour",
      description: "Licor de almendras Amaretto, jugo de limón y jarabe de goma.",
      price: 3500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg5",
      categoryId: "cat_tragos",
      name: "Tropical gin",
      description: "Gin mezclado con bebida energizante tropical o frutas.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg6",
      categoryId: "cat_tragos",
      name: "Tropical gin sabores",
      description: "Variedad de sabores tropicales.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg7",
      categoryId: "cat_tragos",
      name: "Mojito clásico",
      description: "Ron blanco, menta fresca, limón de pica, azúcar de caña y agua gasificada.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg8",
      categoryId: "cat_tragos",
      name: "Mojito Frambuesa",
      description: "Mojito con frambuesas frescas.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg9",
      categoryId: "cat_tragos",
      name: "Mojito Maracuyá",
      description: "Mojito con pulpa de maracuyá.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg10",
      categoryId: "cat_tragos",
      name: "Mojito Frutilla",
      description: "Mojito con frutillas frescas.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg11",
      categoryId: "cat_tragos",
      name: "Mojito Arándano",
      description: "Mojito con arándanos frescos.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg12",
      categoryId: "cat_tragos",
      name: "Ramazzotti rosato tonic",
      description: "Aperitivo Ramazzotti Rosato con agua tónica.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg13",
      categoryId: "cat_tragos",
      name: "Ramazzotti violetto",
      description: "Aperitivo Ramazzotti Violetto con tónica.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg14",
      categoryId: "cat_tragos",
      name: "Aperol Spritz",
      description: "Aperol, espumante Prosecco y un toque de agua con gas.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg15",
      categoryId: "cat_tragos",
      name: "Martini Dry",
      description: "Ginebra y vermut seco con aceituna.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg16",
      categoryId: "cat_tragos",
      name: "Piña colada",
      description: "Ron blanco, crema de coco y jugo de piña.",
      price: 5500,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg17",
      categoryId: "cat_tragos",
      name: "Caipiriña",
      description: "Cachaça brasileña, limón y azúcar de caña machacada.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg18",
      categoryId: "cat_tragos",
      name: "Caipiroska",
      description: "Vodka, limón y azúcar de caña machacada.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg19",
      categoryId: "cat_tragos",
      name: "Tequila Margarita",
      description: "Tequila, triple sec y jugo de limón fresco.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg20",
      categoryId: "cat_tragos",
      name: "Tequila blue",
      description: "Tequila con licor Blue Curaçao y limón.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg21",
      categoryId: "cat_tragos",
      name: "Clavo oxidado",
      description: "Mezcla tradicional de pisco chileno y Drambuie.",
      price: 7500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg22",
      categoryId: "cat_tragos",
      name: "Nobel apple sour",
      description: "Pisco Mistral Nobel con un toque de manzana verde.",
      price: 4500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg23",
      categoryId: "cat_tragos",
      name: "Ruso blanco",
      description: "Vodka, licor de café y crema de leche.",
      price: 5000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg24",
      categoryId: "cat_tragos",
      name: "Ruso negro",
      description: "Vodka y licor de café.",
      price: 4500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg25",
      categoryId: "cat_tragos",
      name: "Pisco sour peruano",
      description: "Pisco peruano, jarabe de goma, jugo de limón y clara de huevo.",
      price: 5000,
      isAvailable: true,
      allergens: ["Huevo"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg26",
      categoryId: "cat_tragos",
      name: "La vaina",
      description: "Cóctel tradicional de oporto, coñac, yema de huevo y canela.",
      price: 5000,
      isAvailable: true,
      allergens: ["Huevo"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg27",
      categoryId: "cat_tragos",
      name: "Mojito corona",
      description: "Mojito clásico servido con una cerveza Corona invertida.",
      price: 7500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg28",
      categoryId: "cat_tragos",
      name: "Primavera Cóctel",
      description: "Mezcla de destilados y jugos naturales de frutas de estación.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg29",
      categoryId: "cat_tragos",
      name: "Laguna azul",
      description: "Vodka, Blue Curaçao y bebida de limón.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg30",
      categoryId: "cat_tragos",
      name: "Darkita clásico",
      description: "Preparación de pisco oscuro y gaseosas oscuras.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg31",
      categoryId: "cat_tragos",
      name: "Daikiri Sabores",
      description: "Ron con hielo picado y fruta a elección (frutilla, piña, etc.).",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg32",
      categoryId: "cat_tragos",
      name: "Tequila Sunrise",
      description: "Tequila, jugo de naranja y granadina.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg33",
      categoryId: "cat_tragos",
      name: "Tom collins",
      description: "Gin, jugo de limón, azúcar y agua con gas.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg34",
      categoryId: "cat_tragos",
      name: "Shot collins",
      description: "Corto de Gin con mezcla cítrica.",
      price: 6000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg35",
      categoryId: "cat_tragos",
      name: "Orgasmo cóctel",
      description: "Baileys, Amaretto y crema de leche.",
      price: 5000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg36",
      categoryId: "cat_tragos",
      name: "Cosmopolitan",
      description: "Vodka, triple sec, jugo de arándanos y jugo de limón fresco.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_trg37",
      categoryId: "cat_tragos",
      name: "Cerveza Corona",
      description: "Cerveza rubia embotellada de 355ml.",
      price: 2500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg38",
      categoryId: "cat_tragos",
      name: "Cerveza Miller",
      description: "Cerveza Miller en botella de 355ml.",
      price: 2500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg39",
      categoryId: "cat_tragos",
      name: "Cerveza Austral calafate",
      description: "Cerveza regional de especialidad con notas de calafate.",
      price: 3500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg40",
      categoryId: "cat_tragos",
      name: "Cerveza Heineken sin alcohol",
      description: "Heineken 0.0 embotellada.",
      price: 2500,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg41",
      categoryId: "cat_tragos",
      name: "Cerveza Kunstmann torobayo Shop",
      description: "Vaso shopero de Kunstmann Torobayo de barril.",
      price: 6000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg42",
      categoryId: "cat_tragos",
      name: "Cerveza Escudo Shop",
      description: "Vaso shopero de Cerveza Escudo.",
      price: 4000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg43",
      categoryId: "cat_tragos",
      name: "Cerveza Royal Shop",
      description: "Vaso shopero de Cerveza Royal Guard.",
      price: 5000,
      isAvailable: true,
      allergens: ["Gluten"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg44",
      categoryId: "cat_tragos",
      name: "Licor Jägermeister (corto)",
      description: "Licor alemán de hierbas digestivas sin bebida.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg45",
      categoryId: "cat_tragos",
      name: "Licor Baileys (corto)",
      description: "Crema de licor irlandés sin bebida.",
      price: 7000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg46",
      categoryId: "cat_tragos",
      name: "Licor Drambuie (corto)",
      description: "Licor escocés de whisky y miel sin bebida.",
      price: 6500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg47",
      categoryId: "cat_tragos",
      name: "Whisky Johnnie Walker red",
      description: "Whisky Red Label sin bebida.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg48",
      categoryId: "cat_tragos",
      name: "Whisky Johnnie Walker Black",
      description: "Whisky Black Label sin bebida.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg49",
      categoryId: "cat_tragos",
      name: "Whisky Johnnie Walker Blonde",
      description: "Whisky Johnnie Walker Blonde sin bebida.",
      price: 7000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg50",
      categoryId: "cat_tragos",
      name: "Whisky Ballantines Finest",
      description: "Whisky Ballantines Finest sin bebida.",
      price: 5000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg51",
      categoryId: "cat_tragos",
      name: "Whisky Chivas Regal 12",
      description: "Whisky Chivas Regal 12 años sin bebida.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg52",
      categoryId: "cat_tragos",
      name: "Whisky Jack Daniels N7",
      description: "Whisky Jack Daniels N7 sin bebida.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg53",
      categoryId: "cat_tragos",
      name: "Whisky Jack Daniels Honey",
      description: "Whisky Jack Daniels Honey con toque de miel sin bebida.",
      price: 8000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg54",
      categoryId: "cat_tragos",
      name: "Whisky Jack Daniels Gentleman",
      description: "Whisky Jack Daniels Gentleman Jack premium sin bebida.",
      price: 9500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg55",
      categoryId: "cat_tragos",
      name: "Pisco Mistral 35°",
      description: "Pisco Mistral 35 grados sin bebida.",
      price: 3500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg56",
      categoryId: "cat_tragos",
      name: "Pisco Mistral Nobel 40°",
      description: "Pisco de guarda Mistral Nobel sin bebida.",
      price: 4500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg57",
      categoryId: "cat_tragos",
      name: "Pisco Mistral Nobel Apple",
      description: "Pisco saborizado de guarda Mistral Nobel Apple sin bebida.",
      price: 4500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg58",
      categoryId: "cat_tragos",
      name: "Pisco Alto del Carmen 35°",
      description: "Pisco Alto del Carmen 35 grados sin bebida.",
      price: 3500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg59",
      categoryId: "cat_tragos",
      name: "Ron Havana Club Añejo Reserva",
      description: "Ron caribeño de reserva sin bebida.",
      price: 4500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg60",
      categoryId: "cat_tragos",
      name: "Ron Barceló Añejo",
      description: "Ron dominicano sin bebida.",
      price: 4000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_trg61",
      categoryId: "cat_tragos",
      name: "Ron Flor de Caña 5 años",
      description: "Ron de guarda nicaragüense sin bebida.",
      price: 5500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },

    // 7. Bebidas y Cafetería (cat_bebidas)
    {
      id: "p_beb1",
      categoryId: "cat_bebidas",
      name: "Jugo Variedad natural",
      description: "Jugos de fruta de estación natural (preparados al instante).",
      price: 2500,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_beb2",
      categoryId: "cat_bebidas",
      name: "Bebida Variedad",
      description: "Bebidas gaseosas individuales en lata (coca-cola, fanta, sprite, etc.).",
      price: 2000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: false
    },
    {
      id: "p_beb3",
      categoryId: "cat_bebidas",
      name: "Limonadas de especialidad",
      description: "Variedad de limonadas: Frambuesa jengibre, Limonada jengibre, Frutilla jengibre o Arándano jengibre.",
      price: 3800,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_beb4",
      categoryId: "cat_bebidas",
      name: "Café Juan Valdez Sabores",
      description: "Café premium de variedad con notas de sabores.",
      price: 2000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_beb5",
      categoryId: "cat_bebidas",
      name: "Té Caliente",
      description: "Tazas de té en infusión.",
      price: 1000,
      isAvailable: true,
      allergens: [],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_beb6",
      categoryId: "cat_bebidas",
      name: "Milo Caliente",
      description: "Taza de leche con chocolate Milo.",
      price: 2000,
      isAvailable: true,
      allergens: ["Lácteos"],
      recipe: [],
      requiresKitchen: true
    },

    // 8. Postres (cat_postres)
    {
      id: "p_pst1",
      categoryId: "cat_postres",
      name: "Creme Brûlée",
      description: "Clásica crema quemada aromatizada con vainilla natural.",
      price: 4000,
      isAvailable: true,
      allergens: ["Lácteos", "Huevo"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_pst2",
      categoryId: "cat_postres",
      name: "Tiramisú casero",
      description: "Postre frío italiano a base de mascarpone y café de especialidad.",
      price: 3500,
      isAvailable: true,
      allergens: ["Lácteos", "Gluten", "Huevo"],
      recipe: [],
      requiresKitchen: true
    },
    {
      id: "p_pst3",
      categoryId: "cat_postres",
      name: "Celestino",
      description: "Panqueque relleno con abundante manjar y azúcar flor.",
      price: 3900,
      isAvailable: true,
      allergens: ["Lácteos", "Gluten", "Huevo"],
      recipe: [],
      requiresKitchen: true
    }
  ],
  ingredients: [
    { id: "i1", name: "Lomo Liso", stock: 5000, unit: "g", minStock: 500 },
    { id: "i2", name: "Pechuga de Pollo", stock: 6000, unit: "g", minStock: 600 },
    { id: "i3", name: "Camarones", stock: 4000, unit: "g", minStock: 400 },
    { id: "i4", name: "Pulpo", stock: 3000, unit: "g", minStock: 300 },
    { id: "i5", name: "Salmón", stock: 3500, unit: "g", minStock: 400 },
    { id: "i6", name: "Merluza", stock: 4000, unit: "g", minStock: 400 },
    { id: "i7", name: "Congrio", stock: 3000, unit: "g", minStock: 300 }
  ],
  orders: [],
  customers: [
    {
      id: "c1", name: "María González", phone: "+56912345678",
      email: "maria@email.com", birthDate: "1985-03-15",
      allergies: ["Gluten"], points: 1250, notes: "Cliente frecuente, prefiere mesa ventana",
    },
    {
      id: "c2", name: "Roberto Silva", phone: "+56987654321",
      email: "roberto@email.com", points: 380, allergies: [],
    },
    {
      id: "c3", name: "Valentina Morales", phone: "+56911223344",
      points: 2100, allergies: ["Mariscos"], notes: "Alergia severa a mariscos",
    },
  ],
  loyaltyTxs: [],
  promotions: [
    {
      id: "pr1", name: "Descuento Bienvenida", code: "HACIENDA10",
      type: PromoType.DISCOUNT, value: 10, active: true, conditions: "Primera visita",
    },
  ],
  payments: [],
  reservations: [],
  shifts: [],
  notifications: [],
  auditLogs: [],
  inventoryTransactions: [],
  onlyViewMenuQr: false,
};
